"""add used_in_training to comments

Revision ID: 28b6a0ef0377
Revises: 063db2a33da9
Create Date: 2026-04-26 07:22:19.282976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28b6a0ef0377'
down_revision: Union[str, Sequence[str], None] = '063db2a33da9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('used_in_training', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'used_in_training')
    # ### end Alembic commands ###
