from enum import Enum

class ResponseSignal(Enum):
    VIDEO_NOT_FOUND = "VIDEO_NOT_FOUND"
    VECTORDB_SEARCH_FAILED = "VECTORDB_SEARCH_FAILED"
    URL_INVALID = "URL_INVALID"
    VIDEO_ANALYSIS_COMPLETE = "VIDEO_ANALYSIS_COMPLETE"
    VIDEO_ANALYSIS_FAILED = "VIDEO_ANALYSIS_FAILED"
    DATABASE_RESET_SUCCESS = "DATABASE_RESET_SUCCESS"
    DATABASE_RESET_FAILED = "DATABASE_RESET_FAILED"
    SENTIMENT_FETCH_SUCCESS = "SENTIMENT_FETCH_SUCCESS"
    SENTIMENT_FETCH_FAILED = "SENTIMENT_FETCH_FAILED"
    
class ErrorMessages:
    INVALID_URL_FORMAT = "URL must start with http:// or https://"
    INVALID_YOUTUBE_URL = "URL must be a YouTube video link"
    VIDEO_NOT_FOUND = "Video information could not be fetched"